--- #YAML:1.0
name:                VCS
version:             0.16
abstract:            (OBSOLETE, USE VCI INSTEAD) Version Control System access in Perl
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
